# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "on_irc"
  s.version = "2.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Olson"]
  s.date = "2012-02-09"
  s.description = "An event driven IRC library with an easy to use DSL"
  s.email = "scott@scott-olson.org"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "LICENSE",
    "Rakefile",
    "VERSION",
    "lib/on_irc.rb",
    "lib/on_irc/callback.rb",
    "lib/on_irc/commands.rb",
    "lib/on_irc/config.rb",
    "lib/on_irc/config_accessor.rb",
    "lib/on_irc/connection.rb",
    "lib/on_irc/dsl_accessor.rb",
    "lib/on_irc/event.rb",
    "lib/on_irc/parser.rb",
    "lib/on_irc/sender.rb",
    "lib/on_irc/server.rb"
  ]
  s.homepage = "http://github.com/tsion/on_irc"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "An event driven IRC library with an easy to use DSL"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
  end
end

